### ISSUE TITLE
how to build colormap

### ISSUE THREAD

**Issue by Liaoqing-up** [cokelaer/colormap#15]
hello, i confused about how to create a colormap using the exists colormap like 'RdYIGn', and then i want to give it a value, and it come back me a color value, so i can use this color to opencv for draw points. 
The purpose i use colormap is to enable my points'color change according to it's x value.
Thanks!

**Comment by cokelaer** [comment]
We could simplify the syntax of course but right now you first create
the cmap and then plot it with Colormap instance:

    from colormap import Colormap, cmap_builder
    
    # could be a cmap from matplotlib of course but you can create the
    # cmap with colormap.cmap_builder:
    cmap = cmap_builder("Greens")

    c = Colormap()
    c.test_colormap(cmap)
