### ISSUE TITLE
More than 3 colors

### ISSUE THREAD

**Issue by lucasglasner** [cokelaer/colormap#16]
Hello, just found this package, great work!,
I wonder... is it possible to make a colormap with more than 3 colors using the package functionality?,
Cheers,
Lucas.

**Comment by cokelaer** [comment]
@lucasglasner yes it is possible. See the online documentation:

at the bottom of https://colormap.readthedocs.io/en/latest/quickstart.html#colormap

in the current example we use 3 colors but yo may add more:

    c = Colormap()
    mycmap = c.cmap( {'red':[1,1,0], 'green':[0,1,.39],  'blue':[0,1,0]})
