### ISSUE TITLE
How is this different then the colormaps already provided in matplotlib?

### ISSUE THREAD

**Issue by jobevers** [cokelaer/colormap#5]
matplotlib already has colormap functionality; I see that you're already using it (https://github.com/cokelaer/colormap/blob/master/src/colormap/colors.py#L717).

What functionality does this library provide that isn't already in matplotlib?

**Comment by cokelaer** [comment]
It is complementary. colormap wraps the colormaps from matplotlib but also 
1. allows users to create their own and to check immediately how it looks like
2. provide a bunch of color triplet conversion. some are in matplotlib, others are not.
