### ISSUE TITLE
Documentation graphic.

### ISSUE THREAD

**Issue by apiszcz** [cokelaer/colormap#6]
Thank you for this module.

The second example image appears to have white around 'center' of the image instead of black as specified.
https://pypi.python.org/pypi/colormap

```
from colormap import Colormap
c = Colormap()
mycmap = c.cmap_linear('red', 'black', 'green')
cmap = c.test_colormap(mycmap)
```

![image](https://user-images.githubusercontent.com/1430861/31861221-5ef8d964-b6f7-11e7-9234-2b39a05477ec.png)

**Comment by cokelaer** [comment]
Fixed. Documentation has been updated.
